### ISSUE TITLE
Los tests en Github me fallan y en local me funcionan 

### ISSUE THREAD

**Issue by OezzaM** [platzi/js-challenge#33]
Hola quería consultar porque estoy teniendo un problema a la hora de correr los tests, cuando los corro localmente en mi computadora me pasan (adjunto captura), pero cuando los corre Github me falla el cuarto y no entiendo porque. 

Desde ya muchas gracias y disculpa las molestias.

¡Un saludo!

Octavio.

![image](https://user-images.githubusercontent.com/67403055/172456261-eb030f6f-5f0f-48d9-8e19-87e1d0e1bb21.png)

**Comment by gndx** [comment]
¿Cuál es el enlace de tu PR, que te dicen el log?

**Comment by OezzaM** [comment]
El PR es este: https://github.com/platzi/js-challenge/pull/14 y el log ahora no me aparece porque hice un cambio en el PR (para probar si se corrían los tests de nuevo ) y se borro el anterior y no se corrieron nuevamente

**Comment by gndx** [comment]
Los tests de tu proyecto están correctos

**Comment by GustavoMartinezFS** [comment]
Mismo problema  [#59](https://github.com/platzi/js-challenge/pull/59/checks)

local : 
![image](https://user-images.githubusercontent.com/57157309/172488512-9636ef3d-5a78-46cf-a5fe-981a9c5fca17.png)

github :
![image](https://user-images.githubusercontent.com/57157309/172488707-fcf2743e-599b-49d2-bf65-3e1520d5adce.png)
 
 Al parecer es por un problema de la API. 🤕

**Comment by gndx** [comment]
> Mismo problema [#59](https://github.com/platzi/js-challenge/pull/59/checks)
> 
> local : ![image](https://user-images.githubusercontent.com/57157309/172488512-9636ef3d-5a78-46cf-a5fe-981a9c5fca17.png)
> 
> github : ![image](https://user-images.githubusercontent.com/57157309/172488707-fcf2743e-599b-49d2-bf65-3e1520d5adce.png)
> 
> Al parecer es por un problema de la API. 🤕

¿Por qué crees que es un problema de API?

**Comment by wolftrax5** [comment]
Mismo problema #151 
<img width="1080" alt="Screen Shot 2022-06-07 at 23 08 39" src="https://user-images.githubusercontent.com/5388080/172529964-936f4566-6ab0-431e-be68-8b7038b23121.png">
<img width="1080" alt="Screen Shot 2022-06-07 at 23 12 40" src="https://user-images.githubusercontent.com/5388080/172530016-60eab328-f696-4d04-88af-18beaf194613.png"> 

en algun PR vi que colocaron un time out, para que pasaran las pruebas,

**Comment by GustavoMartinezFS** [comment]
Yo pude replicar el error agregando un screenshot() que es lo que hace el CI.
![image](https://user-images.githubusercontent.com/57157309/172534488-64c4532c-8fef-4a6f-a81e-735841f0241b.png)

Y como dice wolftrax5, agregando un wait() se puede lograr pasar la prueba.
