### ISSUE TITLE
Que elementos hay que renderizar?

### ISSUE THREAD

**Issue by Jhonaiker2309** [platzi/js-challenge#95]
En el primer render hay que utilizar los primeros 10 elementos del array. Suponiendo que cada vez que se activa Interaction Observer se renderizen 10 elementos más, habría que renderizar los elementos array.slice(5, 15) o los elementos array.slice(15, 25)

**Comment by jairolopezlon** [comment]
@Jhonaiker2309  debes usar la paginación de fakeAPI, te paso la documentación https://fakeapi.platzi.com/doc/products

**Comment by gndx** [comment]
Debes de analizar FakeAPI, la cual tiene una solicitud que te retorna la paginación de esta forma tienes los siguientes 10 elementos, hasta llegar a los 200 que retorna.
